
on:
  push:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  workflow_dispatch:

  jobs:

    windows:
      name: ciostream ${{ matrix.platform }} ${{ matrix.python_arch }} ${{ matrix.spec }}
      runs-on: ${{ matrix.platform }}
      strategy:
        matrix:
          include:
          - platform: windows-2016
            build_arch: x64
            python_arch: x64
            spec: 3.6
      steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install python ${{ matrix.spec }}
        uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.python_arch }}
          python-version: ${{ matrix.spec }}

      - name: Build/Test Package
        shell: bash
        run: |
          python -V
          python -m pip install Cython wheel

          python setup.py build bdist_wheel

